# Netlify configuration for Maugli Blog
# Auto-copied from core-maugli package
# 
# 🔧 CUSTOMIZATION GUIDE:
# - Add "# CUSTOMIZED" comment anywhere to prevent auto-updates
# - Uncomment Bluesky/Supabase plugins after setup in Netlify UI
# - Add your own plugins and they'll be preserved automatically
#

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Обязательные плагины для Astro
[[plugins]]
  package = "netlify-plugin-astro"

# Рекомендуемые плагины для оптимизации
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

# Плагины для интеграций (требуют ручной настройки)
# Раскомментируйте после настройки в Netlify UI:
# ⚠️  После раскомментирования этот файл не будет автоматически обновляться

# Bluesky Custom Domain
# Инструкция: https://app.netlify.com/extensions/bluesky-custom-domain
# [[plugins]]
#   package = "netlify-plugin-bluesky"

# Supabase Integration  
# Инструкция: https://app.netlify.com/extensions/supabase
# [[plugins]]
#   package = "@supabase/netlify-integration"

# Redirects
[[redirects]]
  from = "/blog/feed.xml"
  to = "/rss.xml"
  status = 301

# Headers для безопасности
[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "strict-origin-when-cross-origin"

# Кэширование изображений
[[headers]]
  for = "/img/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

