name: Publish to npm

on:
  push:
    tags:
      - 'v*' # Запускать только при пуше тега вида v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run verify-pack

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
        run: npm publish --access public --provenance
